version: '3.8'

services:
  issuance-service:
    build:
      context: ./backend/issuance-service
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - WORKER_ID=issuance-worker-1
    volumes:
      - issuance-data:/app/data
      - issuance-logs:/app/logs
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  verification-service:
    build:
      context: ./backend/verification-service
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - PORT=3002
      - WORKER_ID=verification-worker-1
    volumes:
      - verification-data:/app/data
      - verification-logs:/app/logs
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    depends_on:
      - issuance-service
      - verification-service

volumes:
  issuance-data:
  issuance-logs:
  verification-data:
  verification-logs:
